### PR TITLE
Proxy support in URL datasource

### PR DESCRIPTION
**Pull request by jsantos17**
[ch9503]

### CODE REVIEW

**Comment by jsantos17** [comment]
Released as `11.0.3-9935112`

**Comment by jsantos17** [comment]
I spent some time trying to test this under Windows with a PAC file but ran into strange permission issues. Will try to test again tomorrow.

**Comment by djspiewak** [comment]
@petrbahr @beckyconning Can we look at this version a bit before we merge and try to get an idea of how well this addresses the issue we're seeing?

**Comment by jsantos17** [comment]
New release that doesn't initialize proxy-vole on each request: `11.0.3-7197f40`.

**Comment by jsantos17** [comment]
New release with latest quasar version: `11.0.4-575f54c`.

**Pull request merged**
